# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Steven Osborne
tagline:          'Home'
description:      'Front-end <a href="https://github.com/nikonmcfly" target="_blank">Developer</a>. Interested in cool tech. Find me tweeting crazy <a href="https://twitter.com/x5tevex" target="_blank">@x5tevex</a>.'

url:              'http://sosborne.co'
baseurl:          ''



email:          	stevenosborne15@gmail.com

author:
  name:           'Steven Osborne'
  url:            'http://sosborne.co'

paginate:         5


github:
  repo:           https://github.com/nikonmcfly
